# Generated by Django 5.1.1 on 2025-03-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrecommendation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recommendation_images/'),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
