# Generated by Django 5.1.5 on 2025-03-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_productrecommendation_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrecommendation',
            name='extra_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
