# Generated by Django 5.1.5 on 2025-03-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_productrecommendation_extra_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrecommendation',
            name='doctor_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
