# Generated by Django 5.1.5 on 2025-03-29 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_productrecommendation_doctor_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrecommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
