# Generated by Django 5.1.5 on 2025-03-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_doctorbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorBooking',
        ),
    ]
