# Generated by Django 5.1.3 on 2025-03-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
