# Generated by Django 5.1.5 on 2025-04-04 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_delete_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorReg',
        ),
    ]
